# Generated by Django 4.0.6 on 2022-07-27 10:18

from django.db import migrations
from django.conf import settings


def update_site_name(apps, _schema_editor):
    """Configures the site domain and name for the configured SITE_ID."""
    site = apps.get_model('sites', 'Site')
    domain = settings.SITE_DOMAIN

    site.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial')
    ]

    operations = [
        migrations.RunPython(update_site_name)
    ]
